// Code generated by mockery v1.0.0
package keymanager

import mock "github.com/stretchr/testify/mock"

// MockKeyManager is an autogenerated mock type for the KeyManager type
type MockKeyManager struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *MockKeyManager) Close() {
	_m.Called()
}

// Create provides a mock function with given fields: r
func (_m *MockKeyManager) Create(r Record) error {
	ret := _m.Called(r)

	var r0 error
	if rf, ok := ret.Get(0).(func(Record) error); ok {
		r0 = rf(r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByUserId provides a mock function with given fields: userid
func (_m *MockKeyManager) FindByUserId(userid string) (Record, error) {
	ret := _m.Called(userid)

	var r0 Record
	if rf, ok := ret.Get(0).(func(string) Record); ok {
		r0 = rf(userid)
	} else {
		r0 = ret.Get(0).(Record)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
