// Code generated by mockery v1.0.0
package keymanager

import db "github.com/thetatoken/vault/db"
import mock "github.com/stretchr/testify/mock"

// MockKeyManager is an autogenerated mock type for the KeyManager type
type MockKeyManager struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *MockKeyManager) Close() {
	_m.Called()
}

// FindByUserId provides a mock function with given fields: userid
func (_m *MockKeyManager) FindByUserId(userid string) (db.Record, error) {
	ret := _m.Called(userid)

	var r0 db.Record
	if rf, ok := ret.Get(0).(func(string) db.Record); ok {
		r0 = rf(userid)
	} else {
		r0 = ret.Get(0).(db.Record)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
